
<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\tModLoader.targets" />
	<PropertyGroup>
		<AssemblyName>DialogueTweak</AssemblyName>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Solaestas.tModLoader.ModBuilder" Version="1.6.1" />
		<PackageReference Update="tModLoader.CodeAssist" Version="0.1.0" />
	</ItemGroup>
</Project>